# AppVeyor configuration file
version: 1.0.{build}

# This section specifies the environment where the build will run
environment:
  matrix:
    - ARDUINO_CLI: ./bin/arduino-cli  # Path to your Arduino CLI tool

# This section defines the steps to run in the CI pipeline
install:
  # Step 1: Checkout the code
  - git clone https://github.com/elara-aerospace/elara-igniter_test_stand
  - cd elara-igniter_test_stand

  # Step 2: Verify Arduino CLI Version
  - echo "Verifying Arduino CLI version..."
  - $ARDUINO_CLI version

  # Step 3: Install Arduino Core
  - echo "Installing Arduino Core (arduino:avr)..."
  - $ARDUINO_CLI core update-index
  - $ARDUINO_CLI core install arduino:avr

# This section defines the build steps for the project
build_script:
  # Step 4: Compile the Arduino Sketch
  - echo "Compiling Arduino sketch..."
  - make compile

# This section runs after the build is completed successfully (optional)
after_build:
  - echo "Build completed successfully!"

# This section defines the deploy steps if needed (not necessary for this example)
deploy:
  # You can add deploy scripts here if necessary (e.g., uploading results to an artifact server)
  - echo "No deploy step defined."

