# GitHub Actions - C/C++ CI
name: C/C++ CI

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build-and-upload:
    runs-on: ubuntu-latest

    steps:
    # Step 1: Checkout the code
    - name: Checkout Code
      uses: actions/checkout@v3

    # Step 2: Verify Arduino CLI Version
    - name: Verify Arduino CLI Version
      run: |
        ./bin/arduino-cli version

    # Step 3: Install Arduino Core
    - name: Install Arduino Core
      run: |
        ./bin/arduino-cli core update-index
        ./bin/arduino-cli core install arduino:avr

    # Step 4: Compile Sketch
    - name: Compile Arduino Sketch
      run: |
        make compile

